import biryani from "@/assets/dish-biryani.jpg";
import butterChicken from "@/assets/dish-butter-chicken.jpg";
import paneerTikka from "@/assets/dish-paneer-tikka.jpg";
import dosa from "@/assets/dish-dosa.jpg";
import chole from "@/assets/dish-chole.jpg";
import tandoori from "@/assets/dish-tandoori.jpg";
import panipuri from "@/assets/dish-panipuri.jpg";
import palak from "@/assets/dish-palak.jpg";
import samosa from "@/assets/dish-samosa.jpg";
import dalMakhani from "@/assets/dish-dal-makhani.jpg";
import chickenTikkaMasala from "@/assets/dish-chicken-tikka-masala.jpg";
import gulabJamun from "@/assets/dish-gulab-jamun.jpg";
import idliSambar from "@/assets/dish-idli-sambar.jpg";
import rajmaChawal from "@/assets/dish-rajma-chawal.jpg";
import alooParatha from "@/assets/dish-aloo-paratha.jpg";
import roganJosh from "@/assets/dish-rogan-josh.jpg";
import mangoLassi from "@/assets/dish-mango-lassi.jpg";
import chickenKorma from "@/assets/dish-chicken-korma.jpg";
import goanFishCurry from "@/assets/dish-goan-fish-curry.jpg";
import vadaPav from "@/assets/dish-vada-pav.jpg";
import kadaiPaneer from "@/assets/dish-kadai-paneer.jpg";
import muttonBiryani from "@/assets/dish-mutton-biryani.jpg";
import papdiChaat from "@/assets/dish-papdi-chaat.jpg";
import kheer from "@/assets/dish-kheer.jpg";
import prawnMasala from "@/assets/dish-prawn-masala.jpg";
import dumAloo from "@/assets/dish-dum-aloo.jpg";
import malaiKofta from "@/assets/dish-malai-kofta.jpg";

export type FamousRecipe = {
  id: string;
  title: string;
  image: string;
  cuisine: string;
  category: string;
  time: string;
  difficulty: "Easy" | "Medium" | "Hard";
  rating: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  description: string;
  ingredients: string[];
  steps: string[];
  youtube: { id: string; title: string; channel: string }[];
  trending?: boolean;
};

export const FAMOUS_RECIPES: FamousRecipe[] = [
  {
    id: "hyderabadi-biryani",
    title: "Hyderabadi Chicken Biryani",
    image: biryani,
    cuisine: "Hyderabadi",
    category: "Biryani",
    time: "1h 20m",
    difficulty: "Hard",
    rating: 4.9,
    calories: 612,
    protein: 32,
    carbs: 68,
    fat: 22,
    description:
      "The crown jewel of Hyderabad — layered basmati rice with saffron, marinated chicken, fried onions and slow dum cooking.",
    ingredients: [
      "500g basmati rice",
      "750g chicken, bone-in",
      "1 cup thick yogurt",
      "2 large onions, sliced & fried (birista)",
      "4 tbsp ghee",
      "1 tsp saffron in warm milk",
      "Whole garam masala (cardamom, cloves, cinnamon)",
      "Mint & coriander leaves",
      "Ginger-garlic paste 2 tbsp",
      "Red chili powder, turmeric, biryani masala",
    ],
    steps: [
      "Marinate chicken in yogurt, ginger-garlic, chili, turmeric and biryani masala for at least 1 hour.",
      "Parboil rice (70% done) with whole spices, salt and a few drops of oil. Drain.",
      "In a heavy pot, layer marinated chicken at the bottom with fried onions and mint.",
      "Layer the parboiled rice on top. Drizzle saffron milk, ghee, mint and remaining birista.",
      "Seal the lid with dough (dum). Cook on high for 4 minutes, then on lowest flame for 25 minutes.",
      "Rest for 10 minutes. Fluff gently and serve with raita and mirchi ka salan.",
    ],
    youtube: [
      { id: "AKnUYi-Jji8", title: "Authentic Hyderabadi Dum Biryani", channel: "Chef Ranveer Brar" },
      { id: "3sLU3GBA0R0", title: "Restaurant Style Chicken Biryani", channel: "Kabita's Kitchen" },
    ],
    trending: true,
  },
  {
    id: "butter-chicken",
    title: "Murgh Makhani (Butter Chicken)",
    image: butterChicken,
    cuisine: "North Indian",
    category: "Butter Chicken",
    time: "45m",
    difficulty: "Medium",
    rating: 4.8,
    calories: 540,
    protein: 36,
    carbs: 18,
    fat: 32,
    description:
      "The Delhi classic — velvety tomato-cashew gravy enriched with cream and butter, hugging tandoor-grilled chicken.",
    ingredients: [
      "600g boneless chicken thighs",
      "1 cup hung curd",
      "6 ripe tomatoes",
      "20 cashews, soaked",
      "100g butter + 100ml cream",
      "Kasuri methi, garam masala",
      "Ginger-garlic paste, red chili powder",
    ],
    steps: [
      "Marinate chicken in curd, ginger-garlic, chili & garam masala for 30 minutes.",
      "Char on a grill or hot pan until edges blacken.",
      "Simmer tomatoes with cashews and spices; blend smooth and strain.",
      "Cook gravy in butter, add cream, then chicken. Simmer 10 minutes.",
      "Finish with crushed kasuri methi and a swirl of cream.",
    ],
    youtube: [
      { id: "a03U45jFxOI", title: "Butter Chicken Restaurant Style", channel: "Chef Ranveer Brar" },
    ],
    trending: true,
  },
  {
    id: "paneer-tikka",
    title: "Paneer Tikka",
    image: paneerTikka,
    cuisine: "North Indian",
    category: "Paneer Tikka",
    time: "30m",
    difficulty: "Easy",
    rating: 4.7,
    calories: 320,
    protein: 18,
    carbs: 12,
    fat: 22,
    description: "Charred paneer cubes in a smoky yogurt marinade with bell peppers and onions.",
    ingredients: [
      "300g paneer, cubed",
      "1 cup thick yogurt",
      "1 capsicum, 1 onion, cubed",
      "Tandoori masala, kasuri methi",
      "Lemon, mustard oil",
    ],
    steps: [
      "Mix yogurt, ginger-garlic, tandoori masala, mustard oil & lemon.",
      "Coat paneer and veggies. Refrigerate 30 minutes.",
      "Skewer and grill/air-fry at 220°C until charred.",
      "Brush with butter, serve with mint chutney.",
    ],
    youtube: [
      { id: "uVQNc8YBcl0", title: "Restaurant Style Paneer Tikka", channel: "Hebbars Kitchen" },
    ],
    trending: true,
  },
  {
    id: "masala-dosa",
    title: "Crispy Masala Dosa",
    image: dosa,
    cuisine: "South Indian",
    category: "Dosa",
    time: "40m",
    difficulty: "Medium",
    rating: 4.8,
    calories: 410,
    protein: 12,
    carbs: 62,
    fat: 14,
    description: "Crispy fermented rice crepe stuffed with spiced potato — South India's iconic breakfast.",
    ingredients: ["Dosa batter", "4 potatoes, boiled", "Mustard seeds, curry leaves", "Onion, green chili", "Turmeric"],
    steps: [
      "Temper mustard seeds, curry leaves, onion and chili in oil.",
      "Add mashed potatoes with turmeric. Mix well.",
      "Spread batter thin on hot tawa. Drizzle ghee.",
      "Place potato filling, fold and serve with sambar and coconut chutney.",
    ],
    youtube: [{ id: "5fBT2tqXVjU", title: "Perfect Crispy Masala Dosa", channel: "Hebbars Kitchen" }],
  },
  {
    id: "chole-bhature",
    title: "Chole Bhature",
    image: chole,
    cuisine: "Punjabi",
    category: "Chole Bhature",
    time: "1h",
    difficulty: "Medium",
    rating: 4.7,
    calories: 720,
    protein: 22,
    carbs: 88,
    fat: 32,
    description: "Pillowy fried bhature with rich, tangy chole — the ultimate Punjabi indulgence.",
    ingredients: ["2 cups chickpeas, soaked", "Chole masala", "Tea bag (for color)", "Maida 2 cups", "Yogurt, baking soda"],
    steps: [
      "Pressure cook chickpeas with tea bag, salt and bay leaf.",
      "Make masala with onion, tomato, ginger-garlic and chole masala.",
      "Combine and simmer until thick.",
      "Knead maida with yogurt and soda. Rest, roll, deep-fry the bhature.",
    ],
    youtube: [{ id: "8E0_eGTeC2Q", title: "Punjabi Chole Bhature", channel: "Kabita's Kitchen" }],
  },
  {
    id: "tandoori-chicken",
    title: "Classic Tandoori Chicken",
    image: tandoori,
    cuisine: "North Indian",
    category: "Tandoori Chicken",
    time: "50m",
    difficulty: "Medium",
    rating: 4.8,
    calories: 380,
    protein: 42,
    carbs: 6,
    fat: 18,
    description: "Bone-in chicken in a smoky yogurt marinade, charred to perfection.",
    ingredients: ["1kg chicken legs", "Hung curd", "Tandoori masala", "Mustard oil", "Lemon"],
    steps: [
      "Score chicken. Marinate with first wet mix for 30 min.",
      "Apply spice marinade. Rest 4+ hours.",
      "Roast at 230°C for 25 min, basting with butter.",
      "Finish on direct flame for char. Serve with lemon and onions.",
    ],
    youtube: [{ id: "iCT7BiFADtY", title: "Tandoori Chicken Without Tandoor", channel: "Chef Ranveer Brar" }],
  },
  {
    id: "pani-puri",
    title: "Pani Puri / Golgappa",
    image: panipuri,
    cuisine: "Street Food",
    category: "Pani Puri",
    time: "25m",
    difficulty: "Easy",
    rating: 4.9,
    calories: 240,
    protein: 6,
    carbs: 42,
    fat: 6,
    description: "India's most beloved street snack — crisp puris filled with spiced water and chutneys.",
    ingredients: ["Puris", "Mint coriander pani", "Tamarind chutney", "Boiled potato & chickpea filling"],
    steps: [
      "Blend mint, coriander, green chili, ginger, jaljeera and water. Chill.",
      "Mix mashed potato, chickpeas, chaat masala and onion for filling.",
      "Crack a hole in puri, fill, dip in pani, eat immediately!",
    ],
    youtube: [{ id: "AdjwzS9wLkc", title: "Pani Puri at Home", channel: "Kabita's Kitchen" }],
    trending: true,
  },
  {
    id: "palak-paneer",
    title: "Palak Paneer",
    image: palak,
    cuisine: "North Indian",
    category: "Palak Paneer",
    time: "35m",
    difficulty: "Easy",
    rating: 4.6,
    calories: 360,
    protein: 20,
    carbs: 14,
    fat: 24,
    description: "Creamy spinach curry with cubes of paneer — wholesome, green and rich.",
    ingredients: ["500g spinach", "250g paneer", "Onion, tomato, ginger-garlic", "Cream, garam masala"],
    steps: [
      "Blanch spinach 2 min, shock in ice water, blend smooth.",
      "Sauté onions, tomatoes, spices. Add puree.",
      "Add paneer, simmer 5 min. Finish with cream.",
    ],
    youtube: [{ id: "umlEbT2dE6Y", title: "Palak Paneer Dhaba Style", channel: "Chef Ranveer Brar" }],
  },
  {
    id: "samosa",
    title: "Punjabi Aloo Samosa",
    image: samosa,
    cuisine: "Street Food",
    category: "Samosa",
    time: "1h",
    difficulty: "Medium",
    rating: 4.8,
    calories: 280,
    protein: 6,
    carbs: 32,
    fat: 14,
    description: "Crispy, flaky pastry triangles stuffed with spiced potato and peas.",
    ingredients: ["Maida, ajwain, ghee", "Potato, peas", "Cumin, coriander, garam masala"],
    steps: [
      "Knead stiff dough with maida, ajwain and ghee. Rest.",
      "Cook potato-pea filling with spices.",
      "Roll, cut, shape cones, fill, seal.",
      "Deep-fry on low-medium until golden and crisp.",
    ],
    youtube: [{ id: "WB-yqtPwTeo", title: "Khasta Punjabi Samosa", channel: "Kabita's Kitchen" }],
    trending: true,
  },
  // ── New dishes ────────────────────────────────────────────────
  {
    id: "dal-makhani",
    title: "Dal Makhani",
    image: dalMakhani,
    cuisine: "North Indian",
    category: "Dal Makhani",
    time: "8h",
    difficulty: "Medium",
    rating: 4.8,
    calories: 420,
    protein: 18,
    carbs: 48,
    fat: 18,
    description:
      "Slow-cooked overnight black lentils enriched with tomato, butter and cream — the soul of a Punjabi dhaba.",
    ingredients: [
      "1 cup whole black urad dal",
      "¼ cup kidney beans",
      "100g butter",
      "4 tomatoes, pureed",
      "100ml fresh cream",
      "2 tbsp ginger-garlic paste",
      "Kasuri methi, garam masala",
      "Red chili powder, coriander powder",
    ],
    steps: [
      "Soak dal and kidney beans overnight. Pressure cook until very soft (8–10 whistles).",
      "Mash half the dal lightly for a creamy texture.",
      "Sauté ginger-garlic in butter, add tomato puree and cook down for 15 minutes.",
      "Add the dal, season and simmer on very low heat for 45 minutes, stirring often.",
      "Stir in cream and kasuri methi. Simmer 10 more minutes.",
      "Serve hot with naan or rice, garnished with butter and fresh coriander.",
    ],
    youtube: [{ id: "dal_makhani_search", title: "Restaurant Style Dal Makhani", channel: "Hebbars Kitchen" }],
    trending: true,
  },
  {
    id: "chicken-tikka-masala",
    title: "Chicken Tikka Masala",
    image: chickenTikkaMasala,
    cuisine: "North Indian",
    category: "Chicken Tikka Masala",
    time: "55m",
    difficulty: "Medium",
    rating: 4.8,
    calories: 490,
    protein: 38,
    carbs: 20,
    fat: 28,
    description:
      "Flame-grilled tikka pieces bathed in a vibrant, creamy spiced tomato masala — bolder than butter chicken.",
    ingredients: [
      "600g boneless chicken, cubed",
      "1 cup yogurt, 2 tbsp tandoori masala",
      "5 tomatoes, 15 cashews (soaked)",
      "2 onions, 1 capsicum",
      "100ml cream",
      "2 tbsp kasuri methi",
      "Ginger-garlic paste, chili powder",
    ],
    steps: [
      "Marinate chicken in yogurt, tandoori masala and lemon for 1 hour.",
      "Grill or pan-char on high heat until nicely blackened.",
      "Blend tomatoes, onion and cashews; cook into a thick sauce.",
      "Add spices, cream and tikka pieces. Simmer 10 minutes.",
      "Finish with kasuri methi and serve with naan.",
    ],
    youtube: [{ id: "tikka_masala_search", title: "Chicken Tikka Masala Restaurant Style", channel: "Chef Ranveer Brar" }],
  },
  {
    id: "gulab-jamun",
    title: "Gulab Jamun",
    image: gulabJamun,
    cuisine: "Dessert",
    category: "Gulab Jamun",
    time: "40m",
    difficulty: "Easy",
    rating: 4.9,
    calories: 310,
    protein: 6,
    carbs: 48,
    fat: 12,
    description:
      "Melt-in-the-mouth milk-solid dumplings soaked in rose and cardamom sugar syrup — India's most beloved dessert.",
    ingredients: [
      "1 cup khoya (mawa)",
      "2 tbsp maida",
      "¼ tsp baking soda",
      "1½ cups sugar",
      "2 cups water",
      "½ tsp rose water",
      "3–4 green cardamom pods",
      "Oil for deep frying",
    ],
    steps: [
      "Knead khoya, maida and baking soda into a soft, smooth dough without cracking.",
      "Make equal small balls — smooth, no cracks, or they'll burst in oil.",
      "Make sugar syrup with water, sugar, cardamom and rose water. Keep warm.",
      "Deep fry on very low heat until evenly dark golden — about 8–10 minutes.",
      "Drop hot jamuns straight into warm syrup. Soak 2 hours before serving.",
      "Garnish with pistachios and silver leaf. Serve warm or at room temperature.",
    ],
    youtube: [{ id: "gulab_jamun_search", title: "Soft Gulab Jamun at Home", channel: "Kabita's Kitchen" }],
    trending: true,
  },
  {
    id: "idli-sambar",
    title: "Idli Sambar",
    image: idliSambar,
    cuisine: "South Indian",
    category: "Idli Sambar",
    time: "45m",
    difficulty: "Easy",
    rating: 4.7,
    calories: 280,
    protein: 10,
    carbs: 52,
    fat: 6,
    description:
      "Pillowy soft steamed rice cakes paired with a tangy toor dal vegetable stew and coconut chutney — South India's breakfast staple.",
    ingredients: [
      "2 cups idli batter (fermented)",
      "1 cup toor dal",
      "Mixed vegetables (carrot, drumstick, potato, pearl onions)",
      "Sambar powder, tamarind paste",
      "Mustard seeds, curry leaves, asafoetida",
      "Dry red chilies, turmeric",
    ],
    steps: [
      "Pour batter into greased idli moulds and steam for 12–15 minutes.",
      "Pressure cook toor dal until mushy. Mash well.",
      "Cook vegetables, tamarind and sambar powder; add dal and simmer 10 minutes.",
      "Temper mustard seeds, curry leaves, red chili and asafoetida in oil; pour into sambar.",
      "Serve hot idli with sambar and coconut chutney.",
    ],
    youtube: [{ id: "idli_sambar_search", title: "Soft Idli Sambar Recipe", channel: "Hebbars Kitchen" }],
  },
  {
    id: "rajma-chawal",
    title: "Rajma Chawal",
    image: rajmaChawal,
    cuisine: "North Indian",
    category: "Rajma Chawal",
    time: "1h 10m",
    difficulty: "Easy",
    rating: 4.7,
    calories: 480,
    protein: 20,
    carbs: 72,
    fat: 12,
    description:
      "Red kidney beans slow-cooked in a thick tomato-onion masala, served with steamed basmati — the ultimate comfort food of North India.",
    ingredients: [
      "1½ cups rajma, soaked overnight",
      "3 large tomatoes, pureed",
      "2 onions, finely chopped",
      "2 tbsp ginger-garlic paste",
      "Rajma masala, red chili powder, turmeric",
      "Bay leaf, cumin, coriander",
      "Steamed basmati rice to serve",
    ],
    steps: [
      "Pressure cook soaked rajma with salt until completely soft.",
      "Sauté onions golden in oil, add ginger-garlic paste, cook 3 minutes.",
      "Add tomato puree and all spices. Cook on medium until oil separates.",
      "Add rajma with its water. Simmer 20 minutes until thick and creamy.",
      "Serve generously over steamed rice with onion salad and pickle.",
    ],
    youtube: [{ id: "rajma_chawal_search", title: "Dhaba Style Rajma Masala", channel: "Kabita's Kitchen" }],
    trending: true,
  },
  {
    id: "aloo-paratha",
    title: "Aloo Paratha",
    image: alooParatha,
    cuisine: "Punjabi",
    category: "Aloo Paratha",
    time: "35m",
    difficulty: "Easy",
    rating: 4.8,
    calories: 350,
    protein: 8,
    carbs: 52,
    fat: 14,
    description:
      "Thick, flaky whole-wheat flatbread stuffed with spiced mashed potato — Punjab's breakfast institution served with white butter and pickle.",
    ingredients: [
      "2 cups whole wheat flour (atta)",
      "4 medium potatoes, boiled & mashed",
      "1 tsp ajwain (carom seeds)",
      "Coriander, green chili, ginger",
      "Chaat masala, red chili flakes",
      "Butter or ghee for cooking",
      "Yogurt and pickle to serve",
    ],
    steps: [
      "Knead atta with water and a pinch of salt into a soft, smooth dough. Rest 20 min.",
      "Mix mashed potato with chopped coriander, green chili, ginger, ajwain and spices.",
      "Roll a dough ball flat, place filling in centre, close and seal edges carefully.",
      "Roll out again gently into a thick paratha (~¼ inch).",
      "Cook on hot tawa with generous ghee until golden and crisp on both sides.",
      "Serve immediately with white butter, yogurt and spicy pickle.",
    ],
    youtube: [{ id: "aloo_paratha_search", title: "Perfect Aloo Paratha Punjabi Style", channel: "Hebbars Kitchen" }],
    trending: true,
  },
  {
    id: "rogan-josh",
    title: "Mutton Rogan Josh",
    image: roganJosh,
    cuisine: "Kashmiri",
    category: "Rogan Josh",
    time: "1h 30m",
    difficulty: "Hard",
    rating: 4.9,
    calories: 520,
    protein: 40,
    carbs: 12,
    fat: 34,
    description:
      "Kashmir's crown jewel — fork-tender mutton slow-braised in an intensely aromatic red gravy of Kashmiri chilies, whole spices and yogurt.",
    ingredients: [
      "1kg mutton, bone-in pieces",
      "1 cup thick yogurt, whisked",
      "8–10 Kashmiri dry red chilies",
      "Fennel powder (saunf), dry ginger powder",
      "Whole spices: cardamom, cloves, cinnamon, bay leaf",
      "Asafoetida (hing), mustard oil",
      "Maval flowers (optional, for deep red colour)",
    ],
    steps: [
      "Heat mustard oil to smoking, add hing and whole spices. Bloom 30 seconds.",
      "Add mutton on high heat. Sear until browned all over — don't rush this step.",
      "Add soaked Kashmiri chili paste and cook until oil separates and colour deepens.",
      "Add yogurt slowly, stirring constantly to prevent curdling.",
      "Add fennel and dry ginger powder. Mix well.",
      "Add water, cover and simmer on low for 60–75 minutes until mutton is tender.",
      "Adjust salt. Serve hot with Kashmiri rice or naan.",
    ],
    youtube: [{ id: "rogan_josh_search", title: "Authentic Kashmiri Rogan Josh", channel: "Chef Ranveer Brar" }],
  },
  {
    id: "mango-lassi",
    title: "Mango Lassi",
    image: mangoLassi,
    cuisine: "Drinks",
    category: "Mango Lassi",
    time: "10m",
    difficulty: "Easy",
    rating: 4.8,
    calories: 220,
    protein: 6,
    carbs: 38,
    fat: 5,
    description:
      "Thick, chilled yogurt blended with ripe Alphonso mango pulp, saffron and cardamom — India's ultimate summer refresher.",
    ingredients: [
      "2 ripe mangoes (or 1 cup Alphonso pulp)",
      "1 cup thick yogurt",
      "½ cup chilled milk",
      "2 tbsp sugar (adjust to taste)",
      "3–4 saffron strands soaked in 1 tbsp warm milk",
      "¼ tsp green cardamom powder",
      "Rose petals and pistachio to garnish",
    ],
    steps: [
      "Peel and chop mangoes. Freeze for 30 minutes for extra chill.",
      "Blend mango, yogurt, milk, sugar and cardamom until silky smooth.",
      "Taste and adjust sugar. Add saffron milk and blend briefly.",
      "Pour into tall glasses. Top with saffron milk swirl and rose petals.",
      "Serve immediately over ice.",
    ],
    youtube: [{ id: "mango_lassi_search", title: "Restaurant Style Mango Lassi", channel: "Kabita's Kitchen" }],
  },
  // ── Batch 2: 10 more dishes ───────────────────────────────────
  {
    id: "chicken-korma",
    title: "Chicken Korma",
    image: chickenKorma,
    cuisine: "Mughlai",
    category: "Chicken Korma",
    time: "1h",
    difficulty: "Medium",
    rating: 4.8,
    calories: 510,
    protein: 34,
    carbs: 14,
    fat: 36,
    description:
      "Mughal royalty on your plate — silky-smooth cashew and yogurt-based gravy with saffron and rose petals hugging tender chicken.",
    ingredients: [
      "700g chicken, bone-in pieces",
      "1 cup hung yogurt",
      "30 cashews, soaked",
      "2 large onions, fried golden (birista)",
      "100ml fresh cream",
      "Saffron in warm milk",
      "Green cardamom, cloves, mace",
      "Rose water, kewra water",
      "Ginger-garlic paste",
    ],
    steps: [
      "Marinate chicken in yogurt, ginger-garlic and mild spices for 1 hour.",
      "Blend fried onions and cashews to a smooth paste.",
      "Cook chicken until sealed. Add cashew-onion paste and whole spices.",
      "Add saffron milk, cream and cook covered on very low heat 30 minutes.",
      "Finish with rose water and kewra. Serve with naan or pulao.",
    ],
    youtube: [{ id: "korma_search", title: "Restaurant Style Chicken Korma", channel: "Chef Ranveer Brar" }],
    trending: true,
  },
  {
    id: "goan-fish-curry",
    title: "Goan Fish Curry",
    image: goanFishCurry,
    cuisine: "Goan",
    category: "Goan Fish Curry",
    time: "35m",
    difficulty: "Easy",
    rating: 4.7,
    calories: 340,
    protein: 36,
    carbs: 12,
    fat: 18,
    description:
      "Sun-soaked coastal Goa in a bowl — tangy, fiery coconut-milk curry with fresh fish, kokum and Kashmiri chilies.",
    ingredients: [
      "500g fish (pomfret or kingfish), steaks",
      "1 coconut, freshly grated",
      "6–8 Kashmiri dry red chilies",
      "1 tsp turmeric",
      "2 tbsp coriander seeds, 1 tsp cumin",
      "4–5 pieces kokum (or tamarind)",
      "Green chilies, curry leaves",
      "Onion, ginger-garlic",
    ],
    steps: [
      "Blend coconut, Kashmiri chilies, coriander seeds, cumin and turmeric with water to a smooth paste.",
      "Fry onion until golden. Add ginger-garlic and cook 2 minutes.",
      "Add the coconut masala paste, cook on medium 5 minutes.",
      "Add water to desired consistency. Add kokum and bring to a boil.",
      "Gently slide in fish pieces. Simmer 8–10 minutes — don't stir, just swirl.",
      "Serve with steamed rice or Goan poi bread.",
    ],
    youtube: [{ id: "goan_fish_search", title: "Authentic Goan Fish Curry", channel: "Chef Ranveer Brar" }],
  },
  {
    id: "vada-pav",
    title: "Vada Pav",
    image: vadaPav,
    cuisine: "Street Food",
    category: "Vada Pav",
    time: "30m",
    difficulty: "Easy",
    rating: 4.9,
    calories: 380,
    protein: 8,
    carbs: 54,
    fat: 16,
    description:
      "Mumbai's soul food — a spiced potato vada in crispy besan batter stuffed into a pav with fiery dry garlic chutney.",
    ingredients: [
      "4 medium potatoes, boiled & mashed",
      "1 cup besan (gram flour)",
      "Mustard seeds, curry leaves, green chili",
      "Turmeric, ginger",
      "6 pav buns",
      "Dry garlic chutney (lahsun chutney)",
      "Green coriander chutney",
      "Oil for deep frying",
    ],
    steps: [
      "Temper mustard seeds, curry leaves and green chili. Add mashed potato with turmeric and ginger. Cool.",
      "Shape into smooth balls. Prepare besan batter with salt, turmeric and water.",
      "Dip potato balls in batter and deep fry until golden and crisp.",
      "Slice pav, spread dry garlic chutney and green chutney.",
      "Place hot vada inside and serve immediately with fried green chili.",
    ],
    youtube: [{ id: "vada_pav_search", title: "Mumbai Style Vada Pav", channel: "Kabita's Kitchen" }],
    trending: true,
  },
  {
    id: "kadai-paneer",
    title: "Kadai Paneer",
    image: kadaiPaneer,
    cuisine: "North Indian",
    category: "Kadai Paneer",
    time: "35m",
    difficulty: "Easy",
    rating: 4.7,
    calories: 390,
    protein: 22,
    carbs: 18,
    fat: 28,
    description:
      "Bold, aromatic and fiery — paneer and capsicum tossed in freshly pounded kadai masala of coriander and dry red chilies.",
    ingredients: [
      "300g paneer, cubed",
      "2 capsicums (red + green), cubed",
      "3 tomatoes, chopped",
      "2 onions, sliced",
      "Kadai masala: 2 tbsp coriander seeds + 4 dry red chilies, coarsely pounded",
      "Ginger julienne, ginger-garlic paste",
      "Kasuri methi, fresh coriander",
    ],
    steps: [
      "Dry roast and coarsely grind coriander seeds and dry red chilies for fresh kadai masala.",
      "Sauté onions until pink. Add ginger-garlic paste and half the kadai masala.",
      "Add tomatoes, cook until oil separates and masala thickens.",
      "Add capsicum, cook 2 minutes so they stay slightly crunchy.",
      "Add paneer, remaining kadai masala, kasuri methi. Toss on high heat.",
      "Garnish with ginger julienne and serve hot with naan or roti.",
    ],
    youtube: [{ id: "kadai_paneer_search", title: "Kadai Paneer Restaurant Style", channel: "Hebbars Kitchen" }],
  },
  {
    id: "mutton-biryani",
    title: "Mutton Dum Biryani",
    image: muttonBiryani,
    cuisine: "Hyderabadi",
    category: "Mutton Biryani",
    time: "2h",
    difficulty: "Hard",
    rating: 4.9,
    calories: 680,
    protein: 36,
    carbs: 72,
    fat: 26,
    description:
      "The king of biryanis — fall-off-the-bone mutton layered with saffron rice, fried onions and slow-cooked under sealed dum.",
    ingredients: [
      "750g mutton, bone-in",
      "500g basmati rice, parboiled",
      "1 cup yogurt, ginger-garlic paste",
      "2 onions, fried (birista)",
      "Saffron milk, rose water, kewra",
      "Biryani masala, whole spices",
      "Ghee, mint, coriander",
      "2 boiled eggs (optional)",
    ],
    steps: [
      "Marinate mutton in yogurt, ginger-garlic, chili and biryani masala overnight.",
      "Brown the mutton in a heavy pot with ghee until sealed.",
      "Parboil rice 70% with whole spices and salt. Drain well.",
      "Layer rice over mutton. Add saffron milk, fried onions, mint and ghee.",
      "Seal pot with dough. Dum cook — 5 min on high, 45 min on lowest flame.",
      "Rest 15 min. Gently open and mix. Serve with raita and salad.",
    ],
    youtube: [{ id: "mutton_biryani_search", title: "Dum Mutton Biryani at Home", channel: "Chef Ranveer Brar" }],
    trending: true,
  },
  {
    id: "papdi-chaat",
    title: "Papdi Chaat",
    image: papdiChaat,
    cuisine: "Street Food",
    category: "Papdi Chaat",
    time: "20m",
    difficulty: "Easy",
    rating: 4.8,
    calories: 260,
    protein: 7,
    carbs: 38,
    fat: 10,
    description:
      "Delhi's favourite chaat — crispy papdi piled high with spiced potatoes, tangy tamarind, green chutney, yogurt and pomegranate.",
    ingredients: [
      "20–24 papdi (crispy fried wafers)",
      "2 potatoes, boiled and cubed",
      "1 cup thick chilled yogurt, beaten",
      "Tamarind-date chutney",
      "Green mint-coriander chutney",
      "Sev (thin fried noodles)",
      "Pomegranate seeds, chaat masala, red chili powder",
    ],
    steps: [
      "Arrange papdi on a flat plate in a single layer.",
      "Top with cubed boiled potato and chickpeas if using.",
      "Spoon chilled yogurt generously over everything.",
      "Drizzle tamarind chutney and green chutney in stripes.",
      "Dust with chaat masala and red chili powder.",
      "Pile sev on top, add pomegranate seeds and serve immediately.",
    ],
    youtube: [{ id: "papdi_chaat_search", title: "Papdi Chaat Delhi Style", channel: "Kabita's Kitchen" }],
    trending: true,
  },
  {
    id: "rice-kheer",
    title: "Rice Kheer",
    image: kheer,
    cuisine: "Dessert",
    category: "Rice Kheer",
    time: "50m",
    difficulty: "Easy",
    rating: 4.8,
    calories: 290,
    protein: 8,
    carbs: 44,
    fat: 9,
    description:
      "India's most cherished festive dessert — rice slow-cooked in full-fat milk until creamy, scented with cardamom and saffron.",
    ingredients: [
      "¼ cup basmati rice, washed",
      "1 litre full-fat milk",
      "5 tbsp sugar (or to taste)",
      "4 green cardamom pods, powdered",
      "A pinch of saffron in warm milk",
      "Cashews, almonds, pistachios (chopped)",
      "Rose petals and silver leaf to garnish",
    ],
    steps: [
      "Soak rice 20 minutes. Bring milk to a boil in a heavy-bottomed pan.",
      "Add drained rice. Cook on medium-low, stirring every few minutes.",
      "Simmer 35–40 minutes until rice is very soft and milk has thickened.",
      "Add sugar, cardamom and saffron milk. Cook 5 more minutes.",
      "Stir in nuts. Serve warm or chilled, garnished with rose petals.",
    ],
    youtube: [{ id: "kheer_search", title: "Creamy Rice Kheer Recipe", channel: "Hebbars Kitchen" }],
  },
  {
    id: "prawn-masala",
    title: "Prawn Masala",
    image: prawnMasala,
    cuisine: "South Indian",
    category: "Prawn Masala",
    time: "30m",
    difficulty: "Medium",
    rating: 4.7,
    calories: 310,
    protein: 30,
    carbs: 10,
    fat: 18,
    description:
      "Juicy tiger prawns cooked in a fiery, aromatic South Indian masala of tomatoes, coconut and curry leaves.",
    ingredients: [
      "500g large prawns, deveined",
      "3 tomatoes, pureed",
      "2 onions, finely chopped",
      "½ cup coconut milk",
      "Curry leaves, mustard seeds, dried red chilies",
      "Turmeric, coriander, red chili powder",
      "Ginger-garlic paste, lemon juice",
    ],
    steps: [
      "Marinate prawns with turmeric, chili powder and lemon. Set aside 15 min.",
      "Temper mustard seeds, curry leaves and dried red chilies in oil.",
      "Add onions; cook golden. Add ginger-garlic, cook 2 minutes.",
      "Add tomato puree, all spices. Cook until oil separates.",
      "Add prawns on high heat. Cook 4–5 min — don't overcook.",
      "Stir in coconut milk, simmer 2 minutes. Serve with rice or appam.",
    ],
    youtube: [{ id: "prawn_masala_search", title: "Spicy Prawn Masala Recipe", channel: "Chef Ranveer Brar" }],
  },
  {
    id: "dum-aloo",
    title: "Kashmiri Dum Aloo",
    image: dumAloo,
    cuisine: "Kashmiri",
    category: "Dum Aloo",
    time: "45m",
    difficulty: "Medium",
    rating: 4.7,
    calories: 330,
    protein: 7,
    carbs: 44,
    fat: 16,
    description:
      "Whole baby potatoes slow-cooked in a fragrant Kashmiri yogurt gravy with fennel, dry ginger and warming whole spices.",
    ingredients: [
      "500g baby potatoes, parboiled and poked",
      "1 cup whisked yogurt",
      "Kashmiri red chili powder (for colour, not heat)",
      "Fennel powder (saunf), dry ginger powder (sonth)",
      "Whole spices: cloves, cardamom, cinnamon",
      "Asafoetida (hing), mustard oil",
    ],
    steps: [
      "Fry baby potatoes in hot mustard oil until golden and crisp. Set aside.",
      "In the same oil, add hing, whole spices and Kashmiri chili powder. Bloom 30 seconds.",
      "Add whisked yogurt very slowly, stirring constantly to prevent splitting.",
      "Add fennel powder and dry ginger. Stir well.",
      "Add fried potatoes. Cook covered on low heat 20 minutes.",
      "Adjust salt. Serve with rice or naan.",
    ],
    youtube: [{ id: "dum_aloo_search", title: "Kashmiri Dum Aloo Recipe", channel: "Chef Ranveer Brar" }],
  },
  {
    id: "malai-kofta",
    title: "Malai Kofta",
    image: malaiKofta,
    cuisine: "North Indian",
    category: "Malai Kofta",
    time: "1h",
    difficulty: "Medium",
    rating: 4.8,
    calories: 460,
    protein: 16,
    carbs: 28,
    fat: 32,
    description:
      "Pillowy paneer and potato dumplings in a luxurious golden tomato-cashew cream gravy — restaurant indulgence at home.",
    ingredients: [
      "200g paneer, grated",
      "2 potatoes, boiled & mashed",
      "2 tbsp cornflour, salt, cardamom",
      "For gravy: 4 tomatoes, 20 cashews, 2 onions",
      "100ml cream",
      "Ginger-garlic paste, coriander, garam masala",
      "Saffron for colour",
    ],
    steps: [
      "Mix paneer, mashed potato, cornflour and spices. Shape into smooth balls.",
      "Deep fry koftas on medium heat until golden. Drain.",
      "Blend onion, tomato and cashew. Cook paste in butter until thick.",
      "Add cream, spices and a pinch of saffron. Simmer 5 minutes.",
      "Add koftas just before serving to prevent softening.",
      "Garnish with cream and serve with naan or pulao.",
    ],
    youtube: [{ id: "malai_kofta_search", title: "Restaurant Style Malai Kofta", channel: "Hebbars Kitchen" }],
    trending: true,
  },
];

export const CATEGORIES = [
  "All",
  "Biryani",
  "Butter Chicken",
  "Paneer Tikka",
  "Dosa",
  "Chole Bhature",
  "Tandoori Chicken",
  "Pani Puri",
  "Palak Paneer",
  "Samosa",
  "Dal Makhani",
  "Chicken Tikka Masala",
  "Gulab Jamun",
  "Idli Sambar",
  "Rajma Chawal",
  "Aloo Paratha",
  "Rogan Josh",
  "Mango Lassi",
  "Chicken Korma",
  "Goan Fish Curry",
  "Vada Pav",
  "Kadai Paneer",
  "Mutton Biryani",
  "Papdi Chaat",
  "Rice Kheer",
  "Prawn Masala",
  "Dum Aloo",
  "Malai Kofta",
];
